#!/bin/bash

# COLOR CODES

B="\e[1;34m"
Y="\e[1;33m"
R="\e[1;31m"
N="\e[0m"

#Note, 1 is for bold feature
#Remember \e[0m is needed every time to go back to neutral color

echo -e "[${B}INF${N}] MESSAGE"
echo -e "[${Y}WAR${N}] MESSAGE"
echo -e "[${R}ERR${N}] MESSAGE"

PRINT () {
 echo -e "${B}"[INF]"${N}" $1
}

ERROR () {
  echo -e "${R}[ERR]${N}" $1
}

COMPONENTS="MONGODB MYSQL REDIS RABBITMQ FRONTEND CART CATALOGUE USER PAYMENT SHIPPING RATINGS DISPATCH

COMPONENT=$1

if [[  -z "${COMPONENT}"  ]] ; then
  INSTALL_COMPONENT="MONGODB MYSQL REDIS RABBITMQ FRONTEND CART CATALOGUE USER PAYMENT SHIPPING RATINGS DISPATCH"
  elif
    case $(COMPONENT) in
      MONGODB|MYSQL|REDIS|RABBITMQ|FRONTEND|CART|CATALOGUE|USER|PAYMENT|SHIPPING|RATINGS|DISPATCH)
      PRINT "SETUP $COMPONENT"
      ;;
    esac
  elif
    *)
      ERROR "INPUT NOT FOUND, PLS TRY AGAIN"
fi


<<UNAUTOMATED_METHOD

PRINT - SETUP MONGODB"
PRINT - SETUP MYSQL"
PRINT - SETUP REDIS"
PRINT - SETUP RABBITMQ"
PRINT - SETUP FRONTEND"
PRINT - SETUP CART"
PRINT - SETUP CATALOGUE"
PRINT - SETUP USER"
PRINT - SETUP PAYMENT"
PRINT - SETUP SHIPPING"
PRINT - SETUP RATINGS"
PRINT - SETUP DISPATCH"

UNAUTOMATED_METHOD


